name: NuGet-Veröffentlichung

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Notwendig für GitVersion

      - name: .NET SDK installieren
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Passe deine .NET-Version an

      - name: GitVersion installieren
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: GitVersion ausführen
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Version in csproj setzen
        run: dotnet build /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: NuGet-Paket erstellen
        run: dotnet pack -c Release -o .
        
      - name: Push NuGet Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./nupkgs/*.nupkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
