name: Publish NuGet Package

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -o ./nupkgs

      - name: Push NuGet Package
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          $files = Get-ChildItem -Path "./nupkgs" -Filter "*.nupkg"
          foreach ($file in $files) {
            Write-Host "Pushing package: $($file.FullName)"
            dotnet nuget push $file.FullName --api-key $env:NUGET_API_KEY --source "https://api.nuget.org/v3/index.json"
          }
